### PR TITLE
Fix https://github.com/viezel/NappJockey/issues/8

### LINKED ISSUE #8: Updating to Titanium SDK 4.1.0
I tried to update my app using the new sdk, but getting this java exception on the console:

06-26 11:10:46.230: E/AndroidRuntime(18644): FATAL EXCEPTION: main
06-26 11:10:46.230: E/AndroidRuntime(18644): java.lang.ClassCastException: dk.napp.jockey.DkNappJockeyWebViewProxy cannot be cast to ti.modules.titanium.ui.WebViewProxy
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at ti.modules.titanium.ui.widget.webview.TiWebViewClient.onPageFinished(TiWebViewClient.java:48)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at dk.napp.jockey.DkNappJockeyWebView$1.onPageFinished(DkNappJockeyWebView.java:47)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at com.jockeyjs.util.ForwardingWebViewClient.onPageFinished(ForwardingWebViewClient.java:53)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:449)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver$1.run(AwContentsClient.java:73)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at android.os.Handler.handleCallback(Handler.java:733)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at android.os.Looper.loop(Looper.java:146)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at android.app.ActivityThread.main(ActivityThread.java:5593)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
06-26 11:10:46.230: E/AndroidRuntime(18644): 	at dalvik.system.NativeStart.main(Native Method)

### PR DESCRIPTION
**Pull request by PSanetra**
Hi,

this PR will fix https://github.com/viezel/NappJockey/issues/8.

I only tested and builded this with sdk 4.0.0.

PSanetra

### CODE REVIEW

**Comment by viezel** [comment]
Looks cool :+1: 
Before I can accept it - you should bump up the min sdk to 4.0. 
Else it will fail in older sdks.

**Comment by PSanetra** [comment]
ok, I changed the minsdk property to 4.0.0.GA

**Comment by viezel** [comment]
super-.

**Comment by sglok** [comment]
The problem remain in SDK 6.2.0 GA, even i have merged the commit ec20c30

**Pull request merged**
